/**
 * Turns icons/*.svg into a typed React module.
 *
 * The SVGs are authored with fill/stroke="currentColor" so a chip inherits the
 * page ink. Inlining them (rather than <img>) is what makes that possible.
 *
 * Run: node scripts/build-icons.mjs
 */
import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const SRC = 'icons'
const OUT = 'components/tech-icons.generated.tsx'

const files = readdirSync(SRC)
  .filter((f) => f.endsWith('.svg'))
  .sort()

const entries = files.map((file) => {
  const id = file.replace(/\.svg$/, '')
  const raw = readFileSync(join(SRC, file), 'utf8')

  const viewBox = raw.match(/viewBox=["']([^"']+)["']/)?.[1]
  if (!viewBox) throw new Error(`${file}: no viewBox`)

  const inner = raw
    .replace(/<\?xml[^>]*\?>/g, '')
    .replace(/<svg[^>]*>/, '')
    .replace(/<\/svg>\s*$/, '')
    .replace(/\bclip-rule=/g, 'clipRule=')
    .replace(/\bfill-rule=/g, 'fillRule=')
    .replace(/\bstroke-width=/g, 'strokeWidth=')
    .replace(/\bstroke-linecap=/g, 'strokeLinecap=')
    .replace(/\bstroke-linejoin=/g, 'strokeLinejoin=')
    .replace(/\bstroke-miterlimit=/g, 'strokeMiterlimit=')
    .replace(/\bclip-path=/g, 'clipPath=')
    .replace(/\bfill-opacity=/g, 'fillOpacity=')
    .replace(/\bstroke-opacity=/g, 'strokeOpacity=')
    .replace(/\bxmlns:xlink=["'][^"']*["']/g, '')
    .replace(/\bxlink:href=/g, 'xlinkHref=')
    // JSX needs style as an object, not a CSS string.
    .replace(/\bstyle=["']([^"']*)["']/g, (_m, css) => {
      const props = css
        .split(';')
        .map((decl) => decl.trim())
        .filter(Boolean)
        .map((decl) => {
          const [prop, ...rest] = decl.split(':')
          const key = prop
            .trim()
            .replace(/-([a-z])/g, (_s, c) => c.toUpperCase())
          return `${key}: ${JSON.stringify(rest.join(':').trim())}`
        })
      return `style={{ ${props.join(', ')} }}`
    })
    .trim()

  return { id, viewBox, inner }
})

const body = `// Generated by scripts/build-icons.mjs — do not edit by hand.
// Source: icons/*.svg

import type { SVGProps } from 'react'

export type IconId =
${entries.map((e) => `  | '${e.id}'`).join('\n')}

export const TECH_ICONS: Record<IconId, (props: SVGProps<SVGSVGElement>) => React.ReactElement> = {
${entries
  .map(
    (e) => `  '${e.id}': (props) => (
    <svg viewBox="${e.viewBox}" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
      ${e.inner}
    </svg>
  ),`,
  )
  .join('\n')}
}
`

writeFileSync(OUT, body)
console.log(`wrote ${OUT} with ${entries.length} icons`)
